# Generated by Django 2.2.24 on 2022-10-12 15:39

from django.db import migrations

def set_value_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_value_new_building),
    ]
