# Generated by Django 2.2.24 on 2022-10-12 15:39

from django.db import migrations

def set_value_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats:
        flat.new_building = flat.construction_year >= 2015
        flat.save()
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_value_new_building),
    ]
