# Generated by Django 4.1.2 on 2022-10-13 18:14

from django.db import migrations

def copy_owner_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        flats = Flat.objects.filter(
            owner=owner.owner_name,
            owners_phonenumber=owner.owners_phonenumber
        )
        owner.owned_flats.set(flats)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_owner_owned_flats_alter_owner_owner_name_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_owner_flat),
    ]

    
