# Generated by Django 4.1.2 on 2022-10-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_rename_owned_flats_owner_flats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='liked_user',
            new_name='liked_users',
        ),
    ]
